version: '2'
services:
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "5000:5000"
    volumes:
    - ./30-output.conf:/etc/logstash/conf.d/30-output.conf
    - .:/app
