version: '2'
services:
  web:
    build: .
    command: bundle exec rails s -p 4000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "4000:4000"
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "5000:5000"
  filebeat:
    image: bargenson/filebeat
    restart: unless-stopped
    environment:
     - LOGSTASH_HOST=elk
     - LOGSTASH_PORT=5044
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - web
    links:
      - "elk:elk"
      - "web:web"
